### ISSUE TITLE
Daily downloads chart zoom broken

### ISSUE THREAD

**Issue by webketje** [pvorb/npm-stat.com#107]
When trying to zoom on the first (daily downloads) chart the selected area keeps jumping and doesn't zoom.
Hitting reset removes the selection but no zoom happens.
This only happens to the first chart, all others work as advertised

Tested this on Firefox 80 & Chromium 85 on Linux Mint.

See attachment for demo (**turn off sound first to spare your ears, system noises**)

https://user-images.githubusercontent.com/1928531/148474616-0b448656-7eb5-4dfe-9bca-354b6e51559e.mp4

**Comment by TiagoCavalcante** [comment]
@webketje seems this already was fixed.

**Comment by webketje** [comment]
@TiagoCavalcante it does seem like it, thx

**Comment by pvorb** [comment]
😕  That's strange. I didn't change anything.

**Comment by TiagoCavalcante** [comment]
@pvorb I guess that was a problem in the plotting library.
