### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by techfort** [pvorb/npm-stat.com#11]
Hi there, great project! It'd be interesting to be able to select a date range and check stats for that period.
And sorry if the facility exists (and somehow i don't see it)

**Comment by pvorb** [comment]
There is such a facility indeed, but I was too lazy to give it some UI controls, so it isn't mentioned anywhere. You can add an additional parameter `period` to the URL, which may contain two dates in ISO 8601 format (only the date without the time) separated by a colon, e.g. `&period=2013-01-01:2014-01-01`.

I think I'm going to hack some `<input type=date>` based solution right now...

**Comment by pvorb** [comment]
PS: Here are two full example URLs.

http://npm-stat.com/charts.html?author=pvorb&period=2013-01-01:2013-12-31
http://npm-stat.com/charts.html?package=clone&period=2013-01-01:2013-12-31

**Comment by pvorb** [comment]
The changes from commit 9283eb3b2110c6b6d43b5ec9a6d2f1a906835cbf are live now: http://npm-stat.com/

The URL format has changed to:

http://npm-stat.com/charts.html?author=pvorb&from=2013-01-01&to=2013-12-31
http://npm-stat.com/charts.html?package=clone&from=2013-01-01&to=2013-12-31

**Comment by techfort** [comment]
Hi Paul, thanks for the prompt response!
If I look up this url http://npm-stat.com/charts.html?package=lokijs&author=techfort&from=2015-01-01&to=2015-03-30 I would expect data for Jan 1st to March 30th 2015, but I get the whole thing since 2013. Am I doing something wrong?

**Comment by pvorb** [comment]
I get the correct results so maybe dropping the cache could solve your issue.

**Comment by techfort** [comment]
Yep, ctrl-R did it. Thanks man!
