### ISSUE TITLE
No data on July 21, and for the last 48 hours

### ISSUE THREAD

**Issue by pygy** [pvorb/npm-stat.com#119]
Hey Paul,

It looks like npm-stat.com hasn't been getting fresh data for the last two days. Also, data for July 21 is susiciously low (0) all across the board

This is what I see for React:
<img width="213" alt="Screenshot 2022-08-03 at 08 29 45" src="https://user-images.githubusercontent.com/54515/182539552-5dcdeec1-13a6-4a2e-a140-9e0be0ec57b8.png">
.

**Comment by pvorb** [comment]
For some reason, npm didn't count any downloads on July 22: https://api.npmjs.org/downloads/point/2022-07-22:2022-07-22

The numbers for the first few days of August are available now, though.

I don't see any errors on npm-stat.com's side.

**Comment by pygy** [comment]
Ah, ok, sorry for the noise.

**Comment by pvorb** [comment]
No problem at all
