### ISSUE TITLE
graphs don't seem to display any more

### ISSUE THREAD

**Issue by 75lb** [pvorb/npm-stat.com#12]
on the author page i'm not seeing weekly and monthly stats..

**Comment by pvorb** [comment]
Do you still see no weekly and monthly stats? I do. What browser are you using?

**Comment by 75lb** [comment]
sorry, i should have provided more info.. i'm seeing the error in the latest Chrome Canary with this URL http://npm-stat.com/charts.html?author=75lb..

![screen shot 2015-04-13 at 23 13 05](https://cloud.githubusercontent.com/assets/1247980/7126627/b2c486ca-e232-11e4-84f9-225a0da2d590.png)

**Comment by pvorb** [comment]
I updated highcharts to version 3.0.10. Does this solve your problem? (Just a wild guess, as I'm not willing to install Canary. I won't see it as my fault until it shows up in Chrome stable.)

**Comment by 75lb** [comment]
works, thanks

**Comment by pvorb** [comment]
Haha, great! :)
