### ISSUE TITLE
GitHub Sponsors?

### ISSUE THREAD

**Issue by electrovir** [pvorb/npm-stat.com#132]
I'd love to donate, but my current FOSS donation pipeline uses GitHub Sponsors. Any chance you could setup a GitHub Sponsors account? :D

**Comment by pvorb** [comment]
Thanks for the idea. Probably it's worth the setup and I can get rid of PayPal.

**Comment by dwelch2344** [comment]
We'd love to share some love also! Keeping eyes here 😄

**Comment by pvorb** [comment]
I applied for GitHub sponsors now, but since I'm living in Germany, some GitHub staff needs to accept my application first.

I guess this URL will show my sponsors page once it's ready: https://github.com/sponsors/pvorb ⏳

**Comment by pvorb** [comment]
I've been approved! Thank you for the suggestion.

https://github.com/sponsors/pvorb

**Comment by electrovir** [comment]
Awesome! Sponsorship started!

**Comment by ljharb** [comment]
3 sponsors in 7 minutes, nice

**Comment by pvorb** [comment]
Wow, you're awesome! 🤩
