### ISSUE TITLE
Days with zero downloads?

### ISSUE THREAD

**Issue by kemeb** [pvorb/npm-stat.com#134]
Checked the download stats for multiple packages and I saw that all of them had 0 downloads for specific days. Is this a known bug or something else?

<img width="974" alt="Screenshot 2024-01-24 at 19 17 38" src="https://github.com/pvorb/npm-stat.com/assets/62247353/e931c746-3fb8-4c6a-af66-e3d00477617d">
<img width="974" alt="Screenshot 2024-01-24 at 19 18 46" src="https://github.com/pvorb/npm-stat.com/assets/62247353/c3b5ad08-e38c-4e87-aea2-cb8727be17b7">
<img width="974" alt="Screenshot 2024-01-24 at 19 20 48" src="https://github.com/pvorb/npm-stat.com/assets/62247353/040f33ab-9b48-43fd-adc7-b465dfef22a0">

**Comment by pvorb** [comment]
Most probably there was a problem with the npm access log analysis process on these days. I can't do anything about it if that happens.
