### ISSUE TITLE
npm-stat.com inaccessible

### ISSUE THREAD

**Issue by Calvin-LL** [pvorb/npm-stat.com#135]
http://npm-stat.com/ seems to have been down for the past day?

**Comment by ozzyogkush** [comment]
It was working for a short time but now I just see a 504 Gateway Timeout

**Comment by christian-bromann** [comment]
Would love the service to come back!

**Comment by pvorb** [comment]
Hey everyone! This is basically just a full disk on the server. I need to delete a few old years.

Sorry for the inconvenience. This site is maintenance-free most of the time, so I haven't looked at the server for months and I don't spend my free time on computer things these days.

I'll try to fix it later today.

**Comment by ljharb** [comment]
Alternatively/regardless, if there's a way to increase available disk space ($), i'd love to arrange help if i can.

**Comment by pvorb** [comment]
![back from the dead](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbTgzaG1heG40bTI1ZHg0bm44ajYybzRodXQwN2hwM2E3cHlvNzN4OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/yoJC2NjczmzoJl80NO/giphy-downsized.gif)

It's back from the dead! 😉
