### ISSUE TITLE
Error 500: Could not fetch data

### ISSUE THREAD

**Issue by fabian-hiller** [pvorb/npm-stat.com#137]
Thank you for npm-stat! I use your services regularly. I get this error when opening the following URL:

Could not fetch data. 500 error {"timestamp":"2024-05-26T01:59:01.474+00:00","status":500,"error":"Internal Server Error","path":"/npm-stat/api/download-counts"}

https://npm-stat.com/charts.html?package=valibot&from=2023-05-24&to=2024-05-24

**Comment by TigersWay** [comment]
+1, with the same thanks and probably same hopes ✨

**Comment by pvorb** [comment]
I'm sorry for the outage. It's now up again.

**Comment by oliviertassinari** [comment]
It seems down on my end.
