### ISSUE TITLE
Update readme example.

### ISSUE THREAD

**Issue by jdalton** [pvorb/npm-stat.com#14]
Underscore's no longer the most depended on package in npm:
https://github.com/pvorb/npm-stat.com/commit/ced32fb4e62ee758e9df713eb3f4b95f152565d7#diff-04c6e90faac2675aa89e2176d2eec7d8R10

**Comment by pvorb** [comment]
:+1: Congratulations!

**Comment by pvorb** [comment]
Fixed by 5b9f2fd5f7154e84a2c01389d003f68232ee82fe

**Comment by jdalton** [comment]
:dancer:
