### ISSUE TITLE
Charts are not showing

### ISSUE THREAD

**Issue by jamesgpearce** [pvorb/npm-stat.com#140]
The tool has been displaying a big red 500 error for the last few days:

`Could not fetch data. 500 error {"timestamp":"2024-06-14T13:20:06.563+00:00","status":500,"error":"Internal Server Error","path":"/npm-stat/api/download-counts"}`

I guess this is on the NPM side...

**Comment by lukekarrys** [comment]
Based on this line, it appears the server requests a URL formatted like `https://api.npmjs.org/downloads/range/2024-06-10:2024-06-13/tinybase` which appears to be working for me as of now.

https://github.com/pvorb/npm-stat.com/blob/1a8f7ae613871bb4d7df12e0fb973f3b027b833a/src/main/java/de/vorb/npmstat/clients/downloads/DownloadsClient.java#L30

```sh
❯ curl -s https://api.npmjs.org/downloads/range/2024-06-10:2024-06-13/tinybase | jq
{
  "start": "2024-06-10",
  "end": "2024-06-13",
  "package": "tinybase",
  "downloads": [
    {
      "downloads": 4003,
      "day": "2024-06-10"
    },
    {
      "downloads": 5070,
      "day": "2024-06-11"
    },
    {
      "downloads": 3717,
      "day": "2024-06-12"
    },
    {
      "downloads": 4541,
      "day": "2024-06-13"
    }
  ]
}
```

**Comment by jamesgpearce** [comment]
(Yep, the raw NPM URL works for me too!)

**Comment by pvorb** [comment]
Thanks for letting me know. It's now up again.

**Comment by pvorb** [comment]
I'm trying to improve the situation. You might experience a few more (short) downtimes.

**Comment by jamesgpearce** [comment]
Amazing - thank you so much!

**Comment by pvorb** [comment]
The server is currently undergoing some storage optimization, which will keep it offline for a few minutes.

**Comment by pvorb** [comment]
I did a (long overdue) OS update that broke a few things. This might take the whole weekend to fix.

Sorry for that.

**Comment by pvorb** [comment]
Or, rather, a whole month. 😬

We're back online now.
