### ISSUE TITLE
Website and API unresponsive

### ISSUE THREAD

**Issue by PyvesB** [pvorb/npm-stat.com#141]
Hello 👋🏻 

It looks like the website is down, possibly a recurrence of #138. Thanks in advance for looking into this!

**Comment by pvorb** [comment]
Yes, I messed up a system update and have to fix a few incompatibilities first. I hope to be able to fix it until tomorrow. Sorry for the inconvenience.

**Comment by pvorb** [comment]
Aaaaand... we're back.

Sorry!
