### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by avindra** [pvorb/npm-stat.com#142]
### Problem

Seeing `404` on `http`, `https` is not connecting at all.

e.g.:

![image](https://github.com/privatenumber/pkg-size.dev/assets/126848/f5673987-1055-423c-b829-13a5f7be3a87)

### Expected behavior

Page should load.

### Minimal reproduction URL

http://npm-stat.com/charts.html?package=axios&from=2021-03-02

**Comment by kubk** [comment]
https://github.com/pvorb/npm-stat.com/issues/141#issuecomment-2171802496

**Comment by pvorb** [comment]
Yeah, sorrrryy. I'm too busy with my day job at the moment, so you'll have to wait for a few more days.

**Comment by pvorb** [comment]
Thanks for staying patient. The site is back online!

**Comment by ljharb** [comment]
@pvorb the site is up, but the actual data ajax endpoints seem to be constantly erroring.

**Comment by ljharb** [comment]
@pvorb seems like maybe it no longer works without an explicit end date? i used to be able to just specify `&from=` and it'd work (so i had a reusable URL that was always up to date)

**Comment by pvorb** [comment]
@ljharb Can you give an example package and time range that I can use to reproduce this?

**Comment by ljharb** [comment]
One example is myself, by author: https://npm-stat.com/charts.html?author=ljharb&from=2010-08-07

**Comment by pvorb** [comment]
@ljharb Try a shorter time period and it will work: https://npm-stat.com/charts.html?author=ljharb&from=2014-08-01

I don't know exactly, but might have to do with compression of historical data that has some limitation I'm not aware of.

**Comment by ljharb** [comment]
hmm, ok - id have assumed that once calculated, old data was cached. Is that not the case?

**Comment by pvorb** [comment]
@ljharb Yes, that's the case. But during the downtime a few weeks ago I had to delete old data in order to get the database to work again. So data from many years ago is no longer available.

**Comment by ljharb** [comment]
@pvorb would funding and/or developer time help restore the old data and functionality, and maintain uptime? My employer may be able to help if so.

**Comment by pvorb** [comment]
@ljharb well, the amount of time I'm willing to spend on this project is very limited. I now have a family and limited spare time to spend on hobby projects. And personally, I moved away from actively working on Node.js project around a decade ago. So there's no easy fix for this.

**Comment by ljharb** [comment]
Gotcha. I'd also be happy to help you maintain it, if that would help too.
