### ISSUE TITLE
Downloads for all packages have been 0 since 28 August

### ISSUE THREAD

**Issue by muhashi** [pvorb/npm-stat.com#144]
![image](https://github.com/user-attachments/assets/da2b5949-4dad-467c-861f-8481284aaa79)

My timezone is UTC+10, so dates may be off by one here

**Comment by davidjbradshaw** [comment]
Issue seems to be with NPM. Same issue on their site and other trackers.

**Comment by muhashi** [comment]
npm issue seems to be fixed!

![image](https://github.com/user-attachments/assets/7444a0d0-a820-4a99-b2a3-5074ce80f104)
