### ISSUE TITLE
Disappearing Dates

### ISSUE THREAD

**Issue by jpodwys** [pvorb/npm-stat.com#15]
Steps to reproduce:

1. Search for a package by name (without specifying a date range)
2. Notice the included dates go up through today
3. From the same screen, search for another package like in step 1
4. Notice that the new package only shows stats for up through yesterday
5. Repeat and notice that stats keep showing for 1 fewer day each time

I've confirmed that this behavior is not due to no stats being available on certain days for certain packages. I've also confirmed that if you stat the search over again from the home page, the query returns all stats as it should.

Thank you for your work!

**Comment by pvorb** [comment]
Thank you for the detailed description. Unfortunately, I'm not able to reproduce your problem.

What browser (version) are you using?

**Comment by jpodwys** [comment]
Thanks for the quick response. I'm on a Mac using Chrome version 44.0.2403.155 (64-bit).

**Comment by jpodwys** [comment]
Confirmed the behavior again today. The date field decrements by one day on subsequent queries. I'll look into a little more.

**Comment by jpodwys** [comment]
OK here's the problem I'm experiencing:

```javascript
new Date('2015-08-18');
```

outputs `Mon Aug 17 2015 18:00:00 GMT-0600 (MDT)`

Notice that the input date says the 18th and the output date, which is used to build the query string, says the 17th.
