### ISSUE TITLE
Issues with large results

### ISSUE THREAD

**Issue by jdalton** [pvorb/npm-stat.com#16]
I'm noticing http://npm-stat.com/charts.html?package=&author=jdalton&from=&to= is starting to fail with:
> An error occured. Please try to reload the page or contact me at [...] if that doesn't help.

**Comment by jdalton** [comment]
Annd it's resolved.

**Comment by pvorb** [comment]
I didn't have the time to look into this. Probably there was a problem in npm's API. Maybe you should try to get fewer downloads in the future. ;)
