### ISSUE TITLE
Date selector broken for timezones < GMT

### ISSUE THREAD

**Issue by fkling** [pvorb/npm-stat.com#17]
If I click on "Show charts", every time both dates are decreased by one day:

![screen shot 2015-12-18 at 6 11 16 pm](https://cloud.githubusercontent.com/assets/179026/11910749/d60afee0-a5b2-11e5-85f7-36c9a3dcffe3.png)
![screen shot 2015-12-18 at 6 11 26 pm](https://cloud.githubusercontent.com/assets/179026/11910750/d787e76a-a5b2-11e5-83df-4d7f5b6a934e.png)

Which means that I actually have to add one day to get the correct time range:

![screen shot 2015-12-18 at 6 16 19 pm](https://cloud.githubusercontent.com/assets/179026/11910763/88801e84-a5b3-11e5-8dea-c9d4d06c41fe.png)

That's because the code uses `getMonth`, `getDate`, etc, which returns the value in *local* time, not UTC. The code should only use UTC date methods.

I currently don't have time to create a PR but will provide one a soon as I can if you don't get to it before.

**Comment by pvorb** [comment]
@fkling I refactored the entire code and now wasn't able to reproduce the problem. To reproduce it, I tried to change my time zone to PDT, but the dates did not change after repeated clicks on "Show charts". Could you please confirm that you are also no longer seeing the problem?

**Comment by fkling** [comment]
Yes, I can confirm that it works as expected now. Thank you!

**Comment by pvorb** [comment]
Great to hear.
