### ISSUE TITLE
"Imaginary" downloads

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pvorb/npm-stat.com#18]
Hello,

Some charts shows downloads months before the first release of npm packages. How can it be possible. It make me reconsider the accuracy of this tool.

Thank you

**Comment by pvorb** [comment]
Can you give me examples so I can have a look?

npm-stat.com just shows the numbers it gets from npm. I can't verify that those are correct.

**Comment by GuillaumeLeclerc** [comment]
`vue-google-maps`. The repo was created about 1 month ago and shows download in july. 

There is no such a bug on the other repo at npm-stats.com.

**Comment by pvorb** [comment]
I can't see any downloads in July. npm-stats.com shows exactly the same data.

**Comment by GuillaumeLeclerc** [comment]
I understand what happened. I filled the package name and owner name. So I got the stats for the owner instead of the package.

I think it would be good to state clearly we should fill one of them and not both.

**Comment by pvorb** [comment]
I should improve the usability by preventing setting both author and package name.

**Comment by pvorb** [comment]
This is fixed in the latest version
