### ISSUE TITLE
Where are you getting dload stats from

### ISSUE THREAD

**Issue by jdalton** [pvorb/npm-stat.com#19]
Hey @pvorb,

I know over the years download stats have changed a bit.

Where are you getting the data from now?
Is it isaacs.iriscouch.com or api.npmjs.org/downloads/?

**Comment by pvorb** [comment]
All numbers are gathered from api.npmjs.org/downloads/. registry.npmjs.org is used to get the list of packages for a user.

Is there something wrong about the numbers?

**Comment by jdalton** [comment]
More curious than anything. I see https://www.npmjs.com/package/lodash that it reports 22,912,485 downloads in the last month while http://npm-stat.com/charts.html?package=lodash reports 15,744,403.

**Comment by pvorb** [comment]
It's more or less a problem of the wording.

On npm-stat.com the last bar shows all downloads of the current month. That means the last bar in the month chart shows all downloads from February 1st until today.

On npmjs.com "last month" actually means "last 30/31 days" which is 8 additional days of January in our case.

You can verify caluclation by running opening http://npm-stat.com/downloads/range/2016-02-01:2016-02-23/lodash and then running the following lines in the developer console:

~~~ js
var data = JSON.parse(document.body.innerText);
var sum = 0;
for (var i in data.downloads) {
    sum += data.downloads[i].downloads;
}
sum;
~~~

It should return `16708695` as shown on npm-stat.com.

If you run the same lines from http://npm-stat.com/downloads/range/2016-01-23:2016-02-23/lodash,  it should say `22912485` which is the same as on npmjs.com.

**Comment by jdalton** [comment]
Ah nice!
