### ISSUE TITLE
More details of how a download was counted

### ISSUE THREAD

**Issue by mkay581** [pvorb/npm-stat.com#24]
Great stats tool! After reading [this article](http://blog.npmjs.org/post/92574016600/numeric-precision-matters-how-npm-download-counts) posted about the data this tool represents, it makes me wonder if there is a way to modify this tool to display where each download was originated from. More specifically, I'm curious to know whether or not a download was made by npm's internal server caching, a bot, or a unique `npm install`.

*Sorry in advance if this was brought up before, but I couldn't find any related issues opened previously on this repo.*

**Comment by pvorb** [comment]
@mkay581 I don't think that is possible. All numbers come from this microservice [npm/download-counts](https://github.com/npm/download-counts).
