### ISSUE TITLE
Scoped Packages?

### ISSUE THREAD

**Issue by clavecoder** [pvorb/npm-stat.com#27]
The [Angular team] has started using [scoped packages], but **npm-stat** [can't see them]. Could support be added for scoped packages?

[Angular team]: http://stackoverflow.com/questions/36667258/understanding-npm-package-prefix-angular-router
[scoped packages]: https://docs.npmjs.com/misc/scope
[can't see them]: https://npm-stat.com/charts.html?package=%40angular%2Fcore&from=2015-07-30&to=2016-07-29

**Comment by pvorb** [comment]
@clavecoder This also has been asked in issue #23.

It's a general issue with npm at the moment. See npm/download-counts#23 for more info on this issue.

**Comment by clavecoder** [comment]
Sorry, missed it. Maybe add "Scoped Packages" to the title? I've subscribed to https://github.com/npm/download-counts/issues/23. Look like a hot button item all around. Interesting that TS is moving there too.

**Comment by pvorb** [comment]
> Sorry, missed it. Maybe add "Scoped Packages" to the title?

I'm no fan of requiring users to skim over existing issues before they are allowed to ask questions. If something is unclear, feel free to ask. ;) I've edited the other issue, though, as you suggested.

> Look like a hot button item all around. Interesting that TS is moving there too.

Definitely. I'd also appreciate if scoped packages would become 1st class citizens soon.
