### ISSUE TITLE
Days off by one

### ISSUE THREAD

**Issue by jdalton** [pvorb/npm-stat.com#33]
Today is Saturday August 13 but the display shows:
<img width="408" src="https://cloud.githubusercontent.com/assets/4303/17646915/03b143c6-6193-11e6-9e58-cc1bd0dd91b5.png">

**Comment by pvorb** [comment]
This is odd. I must have made a mistake when creating Date objects from YYYY-MM-DD date strings from npm. I switched from using plain `new Date(str)` to moment.js.

Can you please give me the following information, so I can try to reproduce the behavior you see:

- What's your timezone?
- When are you seeing this? (Always, around midnight, ...)
- What were the values of the `from` and `to` parameters?

Thanks.

**Comment by jdalton** [comment]
I'm in PDT. This happens any time (doesn't seem to be a near midnight issue) I can see this by just moving the date range out a bit from the current date (though it's still off on the default range).

**Comment by jdalton** [comment]
Any updates?

**Comment by jdalton** [comment]
Ping.

**Comment by pvorb** [comment]
@jdalton I have other priorities at the moment, but I welcome PRs.

**Comment by jdalton** [comment]
Cool. I'll give it a look.

**Comment by jdalton** [comment]
Moved to #37.
