### ISSUE TITLE
Feature: top charts

### ISSUE THREAD

**Issue by wamatt** [pvorb/npm-stat.com#35]
An idea, feel free to use or not. Might be nice to see a chart of top packages over the last year.

Thinking along these lines http://www.tiobe.com/tiobe-index/

**Comment by pvorb** [comment]
You can already compare any packages you want, e.g. https://npm-stat.com/charts.html?package=angular&package=react&package=vue

If you are talking about a comparison of the most downloaded packages of the last year, that will be a problem. There's no backend other than a nginx proxy right now, so I think that wouldn't play nicely with the current approach.

**Comment by wamatt** [comment]
Thats really good to know. Ty!

I would just add, it does take some work to manually create the top lists and compare them, so feature wise it's not quite an equality.

**Comment by pvorb** [comment]
Yes, but I don't want to maintain a set of "top lists".

**Comment by wamatt** [comment]
Np, me neither 😂
