### ISSUE TITLE
NET:ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by jpodwys** [pvorb/npm-stat.com#36]
Trying to load the site in Chrome and getting the following:

![image](https://cloud.githubusercontent.com/assets/5660076/19671863/1bcc1baa-9a2f-11e6-9a14-2ee0f5dda582.png)

First noticed at about 9:10pm MDT.

**Comment by pvorb** [comment]
Thank you for bringing this up. It seems the automatic letsencrypt certificate renewal does not work. I'll fix it when I come home from work this evening.

Am 25.10.2016 05:17 schrieb Joe Podwys <notifications@github.com>:

Trying to load the site in Chrome and getting the following:

 

First noticed at about 9:10pm MDT.

**Comment by jpodwys** [comment]
Awesome, thanks for maintaining this project!

**Comment by pvorb** [comment]
I fixed the issue by simply restarting Nginx.

#### Background
I am using letsencrypt certificates together with [certbot](https://certbot.eff.org/) for automatic certificate renewal. A cron job checks if a certificate needs to be renewed twice per day. Renewal happened one month ago. But what I didn't think about was that Nginx needs to be restarted to load the new certificates into memory!

**Comment by pvorb** [comment]
For the ones who are interested:

Certbot now [ships with an Nginx plugin](https://certbot.eff.org/docs/using.html#nginx), which solves this issue.
