### ISSUE TITLE
Stats by version

### ISSUE THREAD

**Issue by ForbesLindesay** [pvorb/npm-stat.com#4]
It would be really good to be able to get a picture of which versions of a package are being used.  Do you know if that information is available in npm?  If so we could draw a chart of versions people are downloading over time.

**Comment by villesau** [comment]
@pvorb @isaacs is this still the case? Counts per version would be super useful to track how the users have been able to update their packages. This would help with communication and considering backwards compatibility and migration paths etc.

**Comment by pvorb** [comment]
To my knowledge yes, this is still the case.

**Comment by NullVoxPopuli** [comment]
even in 2022? :upside_down_face:

**Comment by NullVoxPopuli** [comment]
(where do we go to look to see if this is supported, so we can stop bothering this issue?)

**Comment by pvorb** [comment]
[Nope, it doesn't look like it's supported now.](https://github.com/npm/registry/blob/master/docs/download-counts.md)
