### ISSUE TITLE
Add some styling

### ISSUE THREAD

**Issue by dlwebdev** [pvorb/npm-stat.com#41]
Would you be interested in someone adding some styling to the page? I'd be happy to chip in if so. Maybe just start with some simple bootstrap elements and a navbar? I see there is a navbar there currently not showing anything.

If you're just trying to keep it simple I totally understand.

This site is very useful, thanks for creating it!

**Comment by pvorb** [comment]
@dlwebdev I don't really see what you want to improve. Can you elaborate on what's annoying with the site in its current form?

**Comment by pvorb** [comment]
As long as I don't get an answer, I assume everything's fine.
