### ISSUE TITLE
API Change: Downloads limited to 18 months, austensibly since 29-08-2017

### ISSUE THREAD

**Issue by icyflame** [pvorb/npm-stat.com#46]
I noticed this yesterday and opened https://github.com/npm/registry/issues/206 which consists of all the links etc.

I opened a ticket with NPM support and this is what they replied with:

![image](https://user-images.githubusercontent.com/3668034/29859999-0b37bc36-8d54-11e7-947d-71a7f75534b1.png)

It seems like the best way to move forward on this website is to break periods that are more than 18 months to multiple API requests and then show the downloads that way.

cc @pvorb

**Comment by pvorb** [comment]
Thanks for pointing this out.
