### ISSUE TITLE
Site stuck loading with no data

### ISSUE THREAD

**Issue by QuantumInformation** [pvorb/npm-stat.com#48]
![image](https://user-images.githubusercontent.com/216566/30422156-fe2520da-9936-11e7-86e8-d9832b1abd2a.png)

**Comment by alanhogan** [comment]
looks like you have a space before your name. i bet #49 fixes this.

**Comment by fibo** [comment]
I confirm that few days ago the website was not loading when I entered a user. Now it is working.
