### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by dpa99c** [pvorb/npm-stat.com#55]
I'm repeatedly getting this error, with no successful loading of the charts after about 10 attempts. 
Each time the loading animation spins until the error message shows.

The URL I'm trying is: https://npm-stat.com/charts.html?author=davealden&from=2017-03-04&to=2018-03-04

So requested URL that's failing is: https://npm-stat.com/api/download-counts?author=davealden&from=2017-03-04&until=2018-03-04

Message content:

    {"message":"feign.FeignException: status 504 reading AuthorsClient#browseAuthors(String,String); content:\n<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"}

Screenshot:

![image](https://user-images.githubusercontent.com/2345062/36998940-851796d4-20b6-11e8-8cc8-081101f6f0c6.png)

**Comment by dpa99c** [comment]
Seems to work now, so temporary issue I guess

**Comment by pvorb** [comment]
Looks like the npm registry was temporarily unavailable.
