### ISSUE TITLE
How to get npm-stats for a closed network/intranet ?

### ISSUE THREAD

**Issue by niteshvudutha** [pvorb/npm-stat.com#56]
Im not sure whether npm-stats works for public repositories alone.
Ours is a closed network.
So, we have our github integrated into client domain as github.client_name.net.
For security reasons, Im not mentioning client name.

Can you tell me what is the approach for getting npm-stats in this scenario?

**Comment by pvorb** [comment]
I'm using the [download counts API](https://github.com/npm/registry/blob/master/docs/download-counts.md) which won't work if you're serving npm from an internal npm instance. I don't get what this has to do with GitHub? npm-stat.com shows download-counts from npmjs.com. Downloads from GitHub are *not* included.
