### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by mrsteele** [pvorb/npm-stat.com#57]
Is it just me or did npm block you?

I get a big red box now and an html error response. If you get into the body of the page it eventually says:

>The owner of this website (api.npmjs.org) has banned your access based on your browser's signature (41630775798c9768-ua21).

Could be just me but I figured I would open something here.

**Comment by CodeMan99** [comment]
I am also getting this response. https://gist.github.com/cba271df7f2f8d11def3e93bc5f0251e

The good news is you can now format your error handling better. This is a JSON object with a single "message" property. Inside the message property there is a string description followed by an HTML page. You might want to `iframe` the HTML?

**Comment by pvorb** [comment]
Thank you for your hints. I asked the folks of npm, Inc. if there is a way around this.

Just presenting you the error page's HTML is quite lousy and leaks many implementation details, I know. That was just the easiest way of giving users a hint of what's going on and makes debugging easier for me. :wink: I'll probably get this right once the service is up again.

**Comment by Dan503** [comment]
I'm getting the same issue.

https://npm-stat.com/charts.html?package=mq-scss&from=2016-11-01&to=2018-05-06

This is the full error message that I am getting:

````
Could not fetch data. 403 error {"message":"feign.FeignException: status 403 reading DownloadsClient#getPackageDownloadsForTimeRange(String,LocalDate,LocalDate); content:\n<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]> <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]> <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<title>Access denied | api.npmjs.org used Cloudflare to restrict access</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n<!--[if lt IE 9]><link rel=\"stylesheet\" id='cf_styles-ie-css' href=\"/cdn-cgi/styles/cf.errors.ie.css\" type=\"text/css\" media=\"screen,projection\" /><![endif]-->\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script><!--<![endif]-->\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script><!--<![endif]-->\n\n\n\n</head>\n<body>\n <div id=\"cf-wrapper\">\n <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n <div class=\"cf-wrapper cf-header cf-error-overview\">\n <h1>\n <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n <span class=\"cf-error-code\">1010</span>\n <small class=\"heading-ray-id\">Ray ID: 41680ad33aea64f9 &bull; 2018-05-06 02:33:28 UTC</small>\n </h1>\n <h2 class=\"cf-subheadline\">Access denied</h2>\n </div><!-- /.header -->\n\n <section></section><!-- spacer -->\n\n <div class=\"cf-section cf-wrapper\">\n <div class=\"cf-columns two\">\n <div class=\"cf-column\">\n <h2 data-translate=\"what_happened\">What happened?</h2>\n <p>The owner of this website (api.npmjs.org) has banned your access based on your browser's signature (41680ad33aea64f9-ua21).</p>\n </div>\n\n \n </div>\n </div><!-- /.section -->\n\n <div class=\"cf-error-footer cf-wrapper\">\n <p>\n <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>41680ad33aea64f9</strong></span>\n <span class=\"cf-footer-separator\">&bull;</span>\n <span class=\"cf-footer-item\"><span>Your IP</span>: 37.120.165.129</span>\n <span class=\"cf-footer-separator\">&bull;</span>\n <span class=\"cf-footer-item\"><span>Performance &amp; security by</span> <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n \n </p>\n</div><!-- /.error-footer -->\n\n\n </div><!-- /#cf-error-details -->\n </div><!-- /#cf-wrapper -->\n\n <script type=\"text/javascript\">\n window._cf_translation = {};\n \n \n</script>\n\n</body>\n</html>\n"}
````
This is what the error looks like when you save the "content" property as an HTML file

----

![html-version-of-error](https://user-images.githubusercontent.com/10610368/39669294-50dccc7c-512b-11e8-8b5f-171ea2ce0f3d.png)

----

Interestingly, at the time of posting (6th May 2018), this error only occurs on the 4th and 5th of May. The charts for everything prior to that work just fine.

https://npm-stat.com/charts.html?package=mq-scss&from=2016-11-01&to=2018-05-03

**Comment by CodeMan99** [comment]
I see that you seem to be making the request server-side and proxying their npmjs API. I wonder if it would be better to do the API request client side? This way ever user of npm-stat.com is also a user of the API, instead of just one location.

This would complicate getting data store centrally in your server of course. It also doesn't help that the npmjs api does not seem to provide a "Modified-Since" or an "ETag" header. Which means you'd need to be able to determine when to send the request for more data.

Perhaps that should be part of the conversation with npmjs? Make the API do conditional requests?

**Comment by pvorb** [comment]
> Interestingly, at the time of posting (6th May 2018), this error only occurs on the 4th, 5th and 6th of May. The charts for everything prior to that work just fine.

@Dan503 That is because I store download counts into a TimescaleDB and only request gaps from the NPM API. This is intended for keeping the pressure on their API as low as possible.

**Comment by pvorb** [comment]
Maybe if more users of npm-stat.com voted for npm/download-counts#41, this issue would more likely attract the attention of npm staff. Just mentioning this because many are voting for the issue of npm-stat.com but the other issue is where the real problem is.

**Comment by pvorb** [comment]
@CodeMan99 Thanks for the hint. I followed your suggestion here: https://github.com/npm/registry/issues/319

**Comment by pvorb** [comment]
The folks at npm disabled Cloudflare's Browser Integrity Check (see https://github.com/npm/registry/issues/319#issuecomment-388981233). That means, npm-stat.com is working again. :tada:

**Comment by mrsteele** [comment]
@pvorb This is great news!

Coincidentally had my a PB for daily downloads, check it out: https://npm-stat.com/charts.html?package=dotenv-webpack
