### ISSUE TITLE
Stats not updated since 5 days

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [pvorb/npm-stat.com#59]
![image](https://user-images.githubusercontent.com/13464885/40901422-cc6a6484-67ed-11e8-9777-5c8db4e8cbbe.png)

**Comment by mrsteele** [comment]
This is definitely an issue with npm. If you look at other services these numbers are the same.

**Comment by SupriyaKalghatgi** [comment]
@mrsteele Which are the other services

**Comment by mrsteele** [comment]
http://npm-stats.org/#/dotenv-webpack
http://www.npmtrends.com/dotenv-webpack
http://npm-stats.com/~packages/dotenv-webpack

Notice all of them drop at the end. Crazy enough I just check npmjs.com exclusively and it also shows no downloads last week: https://www.npmjs.com/package/dotenv-webpack

**Comment by mrsteele** [comment]
Looks like npm updated their status page: https://status.npmjs.org/
They also tweeted: https://twitter.com/npmstatus/status/1003690434760093696

**Comment by pvorb** [comment]
Thanks for bringing this up.

(For some reason I didn't receive email for this issue. Might have to check my notification settings.)

**Comment by mrsteele** [comment]
@Dan503 I think it has sorta always worked like that. NPM has the latest and greatest download counts and the API is normally ~1 day behind.

Not to mention the status page still has the issue being worked on: https://status.npmjs.org/incidents/b4ktc38pypd1

**Comment by SupriyaKalghatgi** [comment]
What about the count of downloads for last week of May?
![image](https://user-images.githubusercontent.com/13464885/41273404-f42cca12-6e36-11e8-9da1-0b7b8a8954cb.png)

**Comment by mrsteele** [comment]
If you choose to watch a couple of big guys, they are all over the place. The status shows they are still working to resolve it so I don't think its working yet.

Also @SupriyaKalghatgi I wouldn't be surprised if that data is lost. It would be great if it was recovered but don't hold your breathe.

**Comment by pvorb** [comment]
From the npm status page:

> **Monitoring** - A fix has been implemented and download counts are returning to normal.
> Jun 13, 16:19 UTC

So probably everything will be fine again by tomorrow.

**Comment by pygy** [comment]
Some packages are [mostly fine](https://npm-stat.com/charts.html?package=compose-regexp) (comparable to what other charting sites show): 

![screen shot 2018-06-14 at 21 43 33](https://user-images.githubusercontent.com/54515/41434486-3127291c-701c-11e8-86f2-c09657c2783e.png)


while others [aren't](https://npm-stat.com/charts.html?package=mithril): 

![screen shot 2018-06-14 at 21 44 01](https://user-images.githubusercontent.com/54515/41434527-5f006e2a-701c-11e8-8184-85bdf459c248.png)

I seem to remember you have a cache somewhere, it would be nice to reset it for the problem dates once you're sure things are in order at NPM.

**Comment by pvorb** [comment]
> I seem to remember you have a cache somewhere, it would be nice to reset it for the problem dates once you're sure things are in order at NPM.

Good point. I deleted all values since 2018-05-24 and most of the values are now available again.

**Comment by SupriyaKalghatgi** [comment]
Stats not updated since June 12
Reopen this issue

**Comment by jdalton** [comment]
Is this something @pvorb can control other than clearing any cache on the site? 
I mean there's nothing actionable here from @pvorb is there?

**Comment by pvorb** [comment]
@jdalton I'll check if I need to clear the cache this evening. Not sure whether there's something else I can do right now.

**Comment by jdalton** [comment]
No worries! Thanks for keeping this great tool kicking 😺

**Comment by SupriyaKalghatgi** [comment]
0 on 12th
fine on 13th
again 0 from 14th

![image](https://user-images.githubusercontent.com/13464885/41515405-7842e16c-72cc-11e8-9379-bc0e4b02af8f.png)

**Comment by mrsteele** [comment]
Just wanted to mention that I believe this to be fixed on npm, but the bug still is intermittent on npm-stat.com. You had mentioned cache earlier and I wouldn't be surprised if that was the case in this instance.

Compared with similar services:
https://npm-stat.com/charts.html?package=dotenv-webpack
vs
https://npmcharts.com/compare/dotenv-webpack

A word of warning is status.npmjs.org is still recognizing the issue but they say its resolved and they are monitoring to be sure it is for sure fixed, so this could still be going on.
https://status.npmjs.org/

**Comment by pvorb** [comment]
That's a little annoying.

I don't know when the numbers returned by the API can be considered final, so I can put them in the cache. I cleared the cache again and will check again in a few days.

**Comment by SupriyaKalghatgi** [comment]
No count from Jun 23rd onwards

**Comment by pvorb** [comment]
I just deployed an update (b2606f5) that changes the caching behavior to the following:

* Numbers that are older than a week will be stored regardless of their value
* After that, numbers are only stored in the cache if they are not equal to zero

I believe this should prevent storing zeros that will change to some non-zero value in the future. This change comes at the cost of additional requests to the NPM API as long as new numbers haven't been calculated.

I'll leave this open for a few more days, so we can see how it works in practice.

**Comment by pvorb** [comment]
My recent update seems to have fixed the problem.

**Comment by mrsteele** [comment]
Hate to say it but the DL counts are at 0 for the past two days. May be back...

**Comment by mrsteele** [comment]
hmm, false alarm maybe cache.

If it happens again I'll take a picture ;)

**Comment by pvorb** [comment]
It could have been an availability problem with the npm api. That's part of why I introduced the cache.

**Comment by donmbelembe** [comment]
This problem is back
