### ISSUE TITLE
Why the first ever recorded date is 2015-02-27

### ISSUE THREAD

**Issue by simov** [pvorb/npm-stat.com#62]
Just wondering. There might be an info about it somewhere but I couldn't find it, and I'm seeing that this project is older than that.

**Comment by pvorb** [comment]
A while ago the people from npm removed all downloads before that day. That's part of why I started storing all values (that have been requested before) in my own database.

**Comment by simov** [comment]
Interesting, I didn't know that they were storing the downloads historically back then. Well, I guess `2015-02-27` is better than nothing. Thanks :+1:

**Comment by pvorb** [comment]
I think the API existed since around mid 2012.
