### ISSUE TITLE
Stats by author doesn't work when you publish a new package

### ISSUE THREAD

**Issue by catcher-in-the-try** [pvorb/npm-stat.com#63]
I use the statistics by author name (instead of by package name).

For a few days after the author publishes a new package, stats won't show with an error "Package `<new-package-name> does not exist`.

Expected: ignore packages that are not cached by npm-stat, generate the stats anyway.

**Comment by pvorb** [comment]
I won't change the behavior for packages that are only a few days old. You simply need to wait until numbers show up. This service is intended for inspecting downloads over long periods of time.
