### ISSUE TITLE
How did you get the origin data from npmjs.com ?

### ISSUE THREAD

**Issue by entronad** [pvorb/npm-stat.com#65]
@pvorb 
I am doing a project witch may use the real-time download count data just like your website.
By reading your code I find it seems that your backend get data from your own database.
So I politely ask that How did your get the origin real-time data from npmjs.com ? Is there any open APIs or did you get it by scraping?

**Comment by pvorb** [comment]
This has been asked several times.

See npm/download-counts

Search for other issues if you want to know more.

**Comment by entronad** [comment]
@pvorb Tanks!
