### ISSUE TITLE
Could not fetch data. 530 error

### ISSUE THREAD

**Issue by karimation** [pvorb/npm-stat.com#66]
`Could not fetch data. 530 error {"message":"feign.FeignException: status 530 reading DownloadsClient#getPackageDownloadsForTimeRange(String,LocalDate,LocalDate); content:\n<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]> <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]> <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<title>Origin DNS error | redis-downloads-2-west.internal.npmjs.com | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n<!--[if lt IE 9]><link rel=\"stylesheet\" id='cf_styles-ie-css' href=\"/cdn-cgi/styles/cf.errors.ie.css\" type=\"text/css\" media=\"screen,projection\" /><![endif]-->\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script><!--<![endif]-->\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script><!--<![endif]-->\n\n\n\n</head>\n<body>\n <div id=\"cf-wrapper\">\n <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n <div class=\"cf-wrapper cf-header cf-error-overview\">\n <h1>\n <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n <span class=\"cf-error-code\">1016</span>\n <small class=\"heading-ray-id\">Ray ID: 452e7dd6f7b59ab2 &bull; 2018-08-31 09:32:43 UTC</small>\n </h1>\n <h2 class=\"cf-subheadline\">Origin DNS error</h2>\n </div><!-- /.header -->\n\n <section></section><!-- spacer -->\n\n <div class=\"cf-section cf-wrapper\">\n <div class=\"cf-columns two\">\n <div class=\"cf-column\">\n <h2 data-translate=\"what_happened\">What happened?</h2>\n <p>You've requested a page on a website (redis-downloads-2-west.internal.npmjs.com) that is on the <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_100x\" target=\"_blank\">Cloudflare</a> network. Cloudflare is currently unable to resolve your requested domain (redis-downloads-2-west.internal.npmjs.com).\n </div>\n\n \n <div class=\"cf-column\">\n <h2 data-translate=\"what_can_i_do\">What can I do?</h2>\n <p><strong>If you are a visitor of this website:</strong><br />Please try again in a few minutes.</p><p><strong>If you are the owner of this website:</strong><br />Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. <a href=\"https://support.cloudflare.com/hc/en-us/articles/234979888-Error-1016-Origin-DNS-error\">Additional troubleshooting information here.</a></p>\n </div>\n \n </div>\n </div><!-- /.section -->\n\n <div class=\"cf-error-footer cf-wrapper\">\n <p>\n <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>452e7dd6f7b59ab2</strong></span>\n <span class=\"cf-footer-separator\">&bull;</span>\n <span class=\"cf-footer-item\"><span>Your IP</span>: 37.120.165.129</span>\n <span class=\"cf-footer-separator\">&bull;</span>\n <span class=\"cf-footer-item\"><span>Performance &amp; security by</span> <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n \n </p>\n</div><!-- /.error-footer -->\n\n\n </div><!-- /#cf-error-details -->\n </div><!-- /#cf-wrapper -->\n\n <script type=\"text/javascript\">\n window._cf_translation = {};\n \n \n</script>\n\n</body>\n</html>\n"}`

**Comment by pvorb** [comment]
So this seems to have been a temporary issue or do you still see 530 errors? I saw one this morning, but now they seem to be gone.

Please re-open if you still see them.
