### ISSUE TITLE
New packages cause error in user level query

### ISSUE THREAD

**Issue by kanekotic** [pvorb/npm-stat.com#69]
Packages that are too new will cause an error while querying a user packages stats. As seen in the next image: 

<img width="538" alt="screen shot 2018-09-30 at 19 40 49" src="https://user-images.githubusercontent.com/3071208/46260633-c4528800-c4e8-11e8-9949-e3df7d7c5a80.png">

Is it possible to add a filter to the query for this cases? 🤔

**Comment by pvorb** [comment]
How could npm-stat tell the difference between packages that do not exist and packages that have no data yet? If your package is new you might be able to figure out the reason on your own, don't you think so?

**Comment by kanekotic** [comment]
sorry I am reading my description and is too vague.
Let me add this is by doing a query for my user, and not for the individual package. Hence my question if its an iteration if there is a way of filter failure of single packages.

**Comment by pvorb** [comment]
Ah, right. I got it now. This could be improved.

**Comment by thetruth97** [comment]
What is this

**Comment by pvorb** [comment]
@thetruth97 Could you elaborate?
