### ISSUE TITLE
Donation link is in German

### ISSUE THREAD

**Issue by dherault** [pvorb/npm-stat.com#71]
When I click on Donation it opens a Paypal page in German. English or my own locale would be appreciated.

**Comment by pvorb** [comment]
Thanks for mentioning. I might be wrong, but I remember it was in English, when I last checked. I'll try to figure out how to change this back to English or use the browser locale.

**Comment by pvorb** [comment]
I'm not quite sure how this works. I changed the locale of the button to en-US (it previously was en-DE, which I've never seen before), but nothing changes for me. The donation page remains German. Probably there is some aggressive caching involved, so this might take a while. If this doesn't work, I'm unsure how to do it.

**Comment by thetruth97** [comment]
I need English

**Comment by pvorb** [comment]
The donation page is in English now. Unfortunately PayPal ignores the browser's settings, so I had to change the **country** [sic] of the donation button to the United States. Changing the language of the button was not enough... :man_facepalming:
