### ISSUE TITLE
Fill in gaps due to 0 downloads issues

### ISSUE THREAD

**Issue by atomiks** [pvorb/npm-stat.com#72]
Your tool is the best one out of the different npm charts in my opinion!

It seems lately npm has had quite a lot of days with 0 downloads due to issues. It would be cool if by default there was an "estimated" downloads (blue dots/lines?) in the chart based on previous downloads to fill them in as they really make the data quite noisy. They would be marked as estimated and noted that there was an issue on that day with the download counter, and also still a toggle to show the "real" (well not really because there was issues) counts.

Crude photoshop of what I'm suggesting:

![Chart gaps](https://i.gyazo.com/31235d80c374eecab3701d802ab2b16e.png)

Edit: I also just considered partial days where the downloads weren't being counted - you can see from the graph that there are unusually low (but nonzero) downloads on certain days. 0 days are obvious, but partial days are less obvious to detect. Maybe if there's a clear anomaly with the data point, use an estimate instead.

**Comment by pvorb** [comment]
Thanks for your request.

I believe this is quite hard to do in highcharts, which I'm using to draw the graphs.

Additionally, this would add a lot of complexity to the service, but the benefit is questionable in my point of view. What does this estimated number really tell you? Probably it would be better to not draw a point at all for days with zeros? I'm not sure.

I think it would be better to improve the calculation process at npm's end, so it doesn't end up with zero downloads. Then this wouldn't be an issue any more.

@atomiks Could you help me in finding out how the calculation is done at the moment? It was once done by [this service](https://github.com/npm/download-counts), but as it hasn't changed in the last two years, it might have been replaced by something else.

**Comment by atomiks** [comment]
It seems like the official npm API returns 0 downloads as well. I think they weren't counting downloads on certain days (due to some issue), so there's no way to recover the data, hence the need to create an estimate to fill it in

**Comment by pvorb** [comment]
As there were no gaps for the last few weeks, I won't implement this feature.
