### ISSUE TITLE
Author download count not working

### ISSUE THREAD

**Issue by larryg01** [pvorb/npm-stat.com#74]
The Author download count is not working its stuck on 5K : meaning that when you have it on your page it reads 5K and stays there but when you click the button and it takes you to the site the count is over 7K : am i correct i thinking that the number should change by the 'k' i.e. 5k 6k 7k etc

**Comment by pvorb** [comment]
How did you include a counter or button in your page? I don't provide such a feature.

**Comment by larryg01** [comment]
it should be the 'project' download count, sorry . my bad not sure what i was thinking
i am using this to show the button on my page https://shields.io/category/downloads

**Comment by pvorb** [comment]
This is not related to npm-stat.com. I don't know how they calculate the numbers. Maybe it's not updated regularly. The numbers on npm-stat.com are polled on demand from the npm API and change every day.
