### ISSUE TITLE
SSL certificate for npm-stat.com is expired

### ISSUE THREAD

**Issue by limonte** [pvorb/npm-stat.com#76]
https://travis-ci.org/sweetalert2/sweetalert2.github.io/builds/520004855

![image](https://user-images.githubusercontent.com/6059356/56098826-814c8500-5f0d-11e9-9e03-a0e357375e71.png)

![image](https://user-images.githubusercontent.com/6059356/56098831-8a3d5680-5f0d-11e9-80ae-53b536f629fa.png)

**Comment by pvorb** [comment]
Sorry, certbot failed to upgrade and thus failed to update the certificate. The certificate is up-to-date again. You should be able to re-run your build-pipeline.

**Comment by limonte** [comment]
All good now, thank you @pvorb for the prompt fix!
