### ISSUE TITLE
502 Bad Gateway on /api/download-counts

### ISSUE THREAD

**Issue by emyann** [pvorb/npm-stat.com#77]
Thank you for this service! 👍🏽 This issue likely is a duplicate of #67 and #55  I guess, but the API call toward `/api/download-counts` fails with a 502 Bad gateway.

**Comment by pvorb** [comment]
I have an idea where this might come from, but I have no time to fix it today. Might get to it tomorrow.

**Comment by emyann** [comment]
@pvorb Take your time, I just wanted to be sure, you were aware of the issue. Thank you in advance for the fix!

**Comment by pvorb** [comment]
It's fixed for now. I'm still not 100 percent sure what caused the failure, so this might come back again.

I'm staying with my family over the Easter holidays and can't get to a laptop instantly. Please reopen this ticket or create a new one if the issue comes back.
