### ISSUE TITLE
Get download stats by author doesn't work anymore

### ISSUE THREAD

**Issue by kanekotic** [pvorb/npm-stat.com#79]
#58 Started happening again.

If you select "Author" in the dropdown npm-stat is not able anymore to get stats by author. It says:
```
Could not fetch data. Does that package exist? Case matters.
feign.FeignException: status 404 reading
AuthorsClient#browseAuthors(String,String); content:
```
Url is https://npm-stat.com/charts.html?author=kanekotic&from=2019-06-03&to=2019-06-12

**Comment by pvorb** [comment]
Yes, I see. Unfortunately I currently have no time to fix this.

**Comment by kanekotic** [comment]
yep no problem. Same here, just wanted to report it, I will have a look if i get a bit of time 😄

**Comment by pvorb** [comment]
I updated the service. This should be fixed now. Please report back if it doesn't work for you.

**Comment by kanekotic** [comment]
check it works great... thanks a lot for the effort of keep the page runing
