### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Juliiii** [pvorb/npm-stat.com#84]
when i try to get the download datas on yesterday, i found it

![image](https://user-images.githubusercontent.com/23744602/69018869-405ba800-09e9-11ea-8610-42154ef5e9c9.png)

please fix it. thx!

**Comment by pvorb** [comment]
I currently have no access to my personal laptop, but I'll look into it asap.

**Comment by Juliiii** [comment]
@pvorb thx.Looking forward to your reply.

**Comment by pvorb** [comment]
Seems to have fixed itself

**Comment by Juliiii** [comment]
@pvorb it seems that it will happen when request yesterday download datas before 10 a.m.  in china.
