### ISSUE TITLE
All Weekly downloads are Zero

### ISSUE THREAD

**Issue by hansiemithun** [pvorb/npm-stat.com#85]
Application seems to be broken or consists of a bug. Considering Vue as an example and tried to get weekly downloads, it shows 0. Tried with other libraries as well, everything is 0

**Comment by pvorb** [comment]
I can't follow.

**Comment by MichalLytek** [comment]
@pvorb 
The last update for many packages is from 17th March:
https://npm-stat.com/charts.html?package=vue&from=2020-03-17&to=2020-03-31
