### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by caroso1222** [pvorb/npm-stat.com#90]
I love this project, thanks for the hard work!

Would you be willing to accept suggestions & PRs to improve the UI a bit? It's fine if your purpose is to keep it simple, too. Just reaching out to offer some help in that regard, if needed.

**Comment by pvorb** [comment]
I'm glad you like it.

Before putting much work in a PR, could you elaborate a litte? What would you improve and how?

**Comment by caroso1222** [comment]
Thanks for replying. Closing this. Shifted focus to something else.
